spring:

  # 指定本地运行环境
  profiles:
   active: dev

  # 项目名称
  application:
    name: user-center

  # 配置数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf-8&useSSL=false
    username: root
    password: zengchao

  # 开启ant风格的请求路径
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 配置Mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.wut.self.pojo

server:
  # 指定接口全局路径前缀
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
  # 指定服务器端口
  port: 8080
