spring:

  # 指定本地运行环境
  profiles:
   active: dev

  # 项目名称
  application:
    name: user-center

  # 配置数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf-8&useSSL=false
    username: root
    password: xxxxxx

  redis:
    # Redis服务器地址
    host: localhost
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 1800000
    # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool.max-active: 20
      # 最大阻塞等待时间(负数表示没限制)
      pool.max-wait: -1
      # 连接池中的最大空闲连接
      pool.max-idle: 5
      # 连接池中的最小空闲连接
      pool.min-idle: 0

  # 配置session 超时时间(单位min)
  session:
    timeout: 86400
    store-type: redis

  # 开启ant风格的请求路径
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 配置Mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.wut.self.pojo

server:
  # 指定接口全局路径前缀
  servlet:
    context-path: /api
  # 指定服务器端口
  port: 8080
